src/components/DocumentationSection.tsx, src/features/startup/startupDialog.tsx
Inline the comment about adding AT client, as that is the only optional step we refer to. Earlier we had multiple optional steps.
Additionally:
Comment out the generic Documentation to Infocenter for now. Will be added back once the Cellular Monitor specific documentation is released. For now just point to the Credential Manager documentation, from Link Monitor.
=> Update how to use

src/features/tracing/nrfml.ts
If monitor-lib finish parsing the trace before we have notified about new packets, the packets that are intermediately stored are lost. This commit enforces a notification of stored packets before trace is stopped.
=> Notify about packets before stopping trace

Changelog.md, src/components/SidePanel/DatabaseFileOverride.tsx, src/components/SidePanel/LoadTraceFile.tsx, src/features/tracing/nrfml.ts
This commit enables the auto detection feature from monitor-lib on readRawTrace, which means that users can select the 'Auto Detect' option for trace database.
When a file is selected, you are prompted with the trace database options, and the default value is **Autoselect**, which will use the monitor-lib auto detection feature.
=> Enable auto detect trace db on Load trace file

src/features/terminal/SourceSelector.tsx
While tracing it should not be possible to change serial port options.
=> Disable Terminal serial port selection while tracing

resources/docs/dashboardFields.ts, src/features/dashboard/Cards/DashboardCard.css, src/features/dashboard/Cards/DashboardCard.tsx, src/features/dashboard/Cards/Device.tsx, src/features/tracingEvents/at/commandProcessors/modemDomainEventNotification.test.ts, src/features/tracingEvents/at/commandProcessors/modemDomainEventNotification.ts, src/features/tracingEvents/at/commandProcessors/packetDomainEvents.test.ts, src/features/tracingEvents/at/commandProcessors/packetDomainEvents.ts, src/features/tracingEvents/at/index.test.ts, src/features/tracingEvents/types.ts
In order to communicate that that user should look into these notifications.
=> Add event notifications to device card

src/features/dashboard/Cards/DashboardCard.tsx
During a refactor the documentation icon with link was placed under the same conditional as sending the related command. Documentation should always be available.
=> fix: documentation link only show while tracing

resources/docs/dashboardFields.ts, src/features/dashboard/Cards/Device.tsx, src/features/dashboard/Cards/LTENetwork.tsx, src/features/tracingEvents/at/commandProcessors/evaluatingConnectionParameters.test.ts, src/features/tracingEvents/at/commandProcessors/evaluatingConnectionParameters.ts, src/features/tracingEvents/at/commandProcessors/extendedSignalQuality.test.ts, src/features/tracingEvents/at/commandProcessors/extendedSignalQuality.ts, src/features/tracingEvents/at/commandProcessors/modemParameters.test.ts, src/features/tracingEvents/at/commandProcessors/modemParameters.ts, src/features/tracingEvents/at/commandProcessors/signalQualityNotification.test.ts, src/features/tracingEvents/at/commandProcessors/signalQualityNotification.ts, src/features/tracingEvents/at/index.test.ts, src/features/tracingEvents/types.ts
Fix: when the index for rsrp, rsrq, and snr, are 255, then the related decibel value should not be calculated, and in the GUI it should display 'Not known or not detectable', as per the documentation.
Feature: When decibel value is available, display the threshold values Excellent, Good, Fair, Poor, and the decibel value in parenthesis. Example (rsrp), 'Excellent (-80 dBm)'.
=> Improve signal quality values

Changelog.md, package.json
This PR will prepare an internal release v1.0.3 to be tested.
-   Option to auto-detect trace database when reading trace file.
-   Option to deselect **Terminal Serial Port**.
-   Dashboard field values can be copied by clicking on the value. The value
will have a blue background when it is possible to copy.
-   Signal quality properties (RSRP, RSRQ, SNR) will show an indication of
Excellent, Good, Fair, or Bad signal strength when it is available.
-   Programming sample could fail the first time programming an application.
-   Signal quality properties (RSRP, RSRQ, SNR) showed incorrect decibel value
when it should have shown "Not known or not detectable".
-   Renamed **Serial port trace capture** to **Modem trace serial port**.
-   When selected device only expose one serial port, the …
=> Prepare release v1.0.3

src/features/dashboard/Cards/DashboardCard.tsx, src/features/dashboard/Dashboard.scss
Also make content more compact, in order to show what content is grouped together. E.g. the vertical spacing between 'REALTED COMMAND' and the following content of commands were too big.
=> Commands were not spaced properly

src/features/programSample/programSample.ts
In this case it could be useful to see the full device information, as it could potentially help us identify what is wrong with the device. Hence, log the whole device, but make sure to JSON.stringify it.
=> fix: logging device as [object Object]

Changelog.md, src/features/programSample/samples.ts
Need to make sure that the target folder exists before copying into the folder.
=> Downloading or copying modem firmware failed

src/features/dashboard/Chart/ChartOptionsDialog.tsx
The actual toggle and its label where on opposite ends of the modal, but they should be closer to each other.
=> Toggle and label should not be to far apart

src/features/dashboard/Chart/Chart.tsx, src/features/dashboard/Chart/chart.scss, src/features/dashboard/Chart/timeSpanDeltaLine.scss
Remove fixed height of the chart, as it should responsively fit with the content of the chart. Rather set min/max on the y-axis, and make sure the fonts and colors are consistent.
This changes the Packet Event Viewer signficantly, with regards to how it looks. May have made the chart iself a bit big, but at least then you see it 🤭
Result:
=> Bump font-size to 12px and fix contrast issues

Changelog.md, package.json
Bumping to major version because we have changed from using the nrf-device-lib binding, to using nrfutil device.
=> Bump to v2.0.0, and update changelog

src/utils/monitorLibLogging.ts
When opening Cellular Monitor, and reading that logging is enabled with log level "0", makes it sound like the user should expect to get logging from nrf-monitor-lib.
Make it more understandable when the logging is off, and when it is on, so that when the user actually turns it on, then the user can be confident that the logging is on.
=> fix: make log messages more intuitive

src/features/programSample/programSample.ts
Thingy91 is not a devkit, and will never have the devkit property. It does however, have the productId property on its serialPorts.
=> fix: accessed wrong property to determine device

doc/docs/overview.md, doc/docs/requirements.md, doc/docs/revision_history.md, src/features/startup/startupDialog.tsx
Fixed outdated information on the startup dialog and in the docs. NRFU-1011.
=> modem_trace_snippet: fix docs and dialog

.github/workflows/zoomin-publish.yml, README.md, doc/docs/capturing.md, doc/docs/index.md, doc/docs/installing.md, doc/docs/loading.md, doc/docs/memfault_in_production.md, doc/docs/overview.md, doc/docs/preparing.md, doc/docs/requirements.md, doc/docs/revision_history.md, doc/docs/troubleshooting.md, doc/docs/viewing.md, doc/docs/viewing_rtt.md, doc/mkdocs.yml, doc/zoomin/custom.properties
Dropped nRF Connect from app name.
Updated copyright year.
Removed unused extensions.
Added app_name abbreviation.
NCD-1066.
=> doc: rename app + other edits

Changelog.md, package-lock.json, package.json, src/features/certificateManager/CertificateManager.tsx, src/index.scss
**Before vs After:**
**1)**
**2)**
**3)**
**4) Before**
**4) After**
Note: not sure that wrapping text in the info alert is an issue, for smaller window dimentions can be considered as a feature, so please comment on this if you disagree with the change
=> Certificate manager tab fixes

src/features/programSample/samples.ts, src/features/tracing/traceDatabase.ts
Because there are redirects in place for the old download locations, it is not critical to update this. However it is nice to point to the right location and it avoids using those redirects.
=> Use files.nordicsemi.com for file downloads

doc/docs/index.md, doc/docs/overview.md, doc/docs/preparing.md, doc/docs/requirements.md, doc/docs/revision_history.md, doc/docs/troubleshooting.md
Added information about Program device only visible for
the nRF9160 DK and Nordic Thingy:91.
Edited the requirements section.
Made corresponding changes on other pages.
NCD-1364.
=> doc: custom board clarifications
